# Site Settings
title: cayy's home
description: ""
url: "https://blog.caysgoodies.xyz"
baseurl: "" 
repository: "cayrrs/blog" 




plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist


author:
  name: "cayy"
  avatar: "https://avatars.githubusercontent.com/u/177371607?v=4"
  bio: "rec roomer and vr enjoyer"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/cayrrs"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post  
  - scope:
      path: ""
      type: pages
    values:
      layout: default

navigation:
  - name: Home
    link: /
  - name: Blog
    link: /blog/   



include:
  - admin   
