# Site Settings
title: cayy's blog
description: "my blog where i say shit"
url: "https://blog.caysgoodies.xyz"
baseurl: "" 
repository: "cayrrs/blog" 


remote_theme: "knhash/jekyllBear"


plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist


author:
  name: "cayy"
  avatar: "https://avatars.githubusercontent.com/u/177371607?v=4"
  bio: "rec roomer and vr enjoyer"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/cayrrs"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: false
      related: false

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/cayrrs/blog"   



include:
  - admin   
